---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fhsnzrgr/api-public
    - /usr/bin/scp -r alerts/ $DEPLOYPATH
    - /usr/bin/scp -r articles/ $DEPLOYPATH
    - /usr/bin/scp -r clubs/ $DEPLOYPATH
    - /usr/bin/scp -r extras/ $DEPLOYPATH
    - /usr/bin/scp -r pages/ $DEPLOYPATH
    - /usr/bin/scp cpanel_start.js $DEPLOYPATH
    - /usr/bin/scp index.js $DEPLOYPATH
    - /usr/bin/scp nodemon.json $DEPLOYPATH
    - /usr/bin/scp package.json $DEPLOYPATH
    - touch $DEPLOYPATH/tmp/restart.txt