---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fhsnzrgr/api-development
    - /usr/bin/scp -R alerts/ $DEPLOYPATH
    - /usr/bin/scp -R articles/ $DEPLOYPATH
    - /usr/bin/scp -R clubs/ $DEPLOYPATH
    - /usr/bin/scp -R extras/ $DEPLOYPATH
    - /usr/bin/scp -R pages/ $DEPLOYPATH
    - /usr/bin/scp -R cpanel_start.js $DEPLOYPATH
    - /usr/bin/scp -R index.js $DEPLOYPATH
    - /usr/bin/scp -R nodemon.json $DEPLOYPATH
    - /usr/bin/scp -R package.json $DEPLOYPATH